kind: pipeline
name: default

steps:

- name: publish
  image: plugins/docker
  settings:
    registry: docker.io
    repo: debianmaster/go-welcome1
  when:
    event: [ promote ]
    target: [ staging ]

- name: publish_to_prod
  image: plugins/docker
  settings:
    registry: registry.heroku.com
    repo: registry.heroku.com/my-production-app/web
  when:
    event: [ promote ]
    target: [ production ]
