
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-welcome
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-welcome
  template:
    metadata:
      labels:
        app: go-welcome
    spec:
      containers:
      - name: go-welcome
        image: ghcr.io/debianmaster/go-welcome:latest
        ports:
        - containerPort: 8080
