
name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build and test
      run: |
        make build
        make test

    - name: Push Docker image to GitHub Container Registry
      run: |
        docker login ghcr.io -u $GITHUB_ACTOR -p $GITHUB_TOKEN
        docker build -t ghcr.io/debianmaster/go-welcome .
        docker push ghcr.io/debianmaster/go-welcome

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployment.yaml
