name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:


    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Set up Go
      uses: k8s-actions/golang@v0.1       
    - name: build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        go mod download -json && go mod vendor
        make server && make manager && make agent

        

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v1
      - name: Set up Go
        uses: k8s-actions/golang@v0.1 
      - name: test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          go mod download -json && go mod vendor
          go test -coverprofile=coverage.out $(go list ./... | grep -v /vendor/)
          go tool cover -func=coverage.out
    
      - name: Upload Coverage report to CodeCov
        uses: codecov/codecov-action@v1.0.0
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.txt
